In [3]:
#with open('./drive/MyDrive/ReadMe.md','w') as f:
 # data = f.write('*반가워요')

# 넘파이(numpy)

 - ndim : 축의 개수
 - shape : 배열의 차원정보
 - size : 배열안에 있는 원소의 총 개수
 - dtype : 배열 원소의 자료형

In [10]:
# pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry,type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry[3])
print(narry[2:4])

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
3
[2 3]


In [14]:
narr1 = np.array([1,2,3,4])
narr2 = np.array([1,2,'a','b'])
narr3 = np.array([1,2,'a','b'],dtype='str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' 'a' 'b'] <U1


In [85]:
narr4 = np.zeros((2,2),dtype='int64')
narr5 = np.ones((2,2))
narr6 = np.full((3,3),3)
narr7 = np.full((3,3),'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5,endpoint=False)
narr10 = np.linspace(0,100,20)
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4))
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5))
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6))
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7))
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8))
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9))
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 0. 20. 40. 60. 80.] 1 float64 (5,) 5 <class 'numpy.ndarray'>
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ] 1 float64 (20,) 20 <class 'numpy.ndarray'>


## 2차원 배열

In [39]:
print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim,arr1.dtype,arr1.shape,arr1.size, type(arr1))


[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [42]:
arr2 =np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 =np.array(np.arange(1,10)).reshape(3,3)
arr4 =np.array(np.arange(1,11)).reshape(2,5)
arr5 =np.array(np.arange(1,11)).reshape(5,2)
arr6 =np.array(np.arange(1,28)).reshape(3,3,3)
print ('차원 : ',arr2.ndim,'데이터타입 : ', arr2.dtype,'형태 : ', arr2.shape,'크기 : ', arr2.size, type(arr2),arr2)
print ('차원 : ',arr3.ndim,'데이터타입 : ', arr3.dtype,'형태 : ', arr3.shape,'크기 : ', arr3.size, type(arr3),arr3)
print ('차원 : ',arr4.ndim,'데이터타입 : ', arr4.dtype,'형태 : ', arr4.shape,'크기 : ', arr4.size, type(arr4),arr4)
print ('차원 : ',arr5.ndim,'데이터타입 : ', arr5.dtype,'형태 : ', arr5.shape,'크기 : ', arr5.size, type(arr5),arr5)
print ('차원 : ',arr6.ndim,'데이터타입 : ', arr6.dtype,'형태 : ', arr6.shape,'크기 : ', arr6.size, type(arr6),arr6)

차원 :  2 데이터타입 :  int64 형태 :  (3, 3) 크기 :  9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원 :  2 데이터타입 :  int64 형태 :  (3, 3) 크기 :  9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원 :  2 데이터타입 :  int64 형태 :  (2, 5) 크기 :  10 <class 'numpy.ndarray'> [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
차원 :  2 데이터타입 :  int64 형태 :  (5, 2) 크기 :  10 <class 'numpy.ndarray'> [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
차원 :  3 데이터타입 :  int64 형태 :  (3, 3, 3) 크기 :  27 <class 'numpy.ndarray'> [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [88]:
t1 =np.array(np.arange(1,22)).reshape(3,7)
t2 =np.array(np.arange(1,8)).reshape(7,1)
t3 =np.array(np.arange(1,11)).reshape(5,2)
t4 =np.array(np.arange(1,22)).reshape(3,7)
t5 =np.array(np.arange(1,13)).reshape(4,3,1)
print (t1)
print ('===============================')
print (t2)
print ('===============================')
print (t3)
print ('===============================')
print (t4)
print ('===============================')
print (t5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [99]:
t4[0:3,3:8]

array([[ 4,  5,  6,  7],
       [11, 12, 13, 14],
       [18, 19, 20, 21]])

In [103]:
# test
print(t4 % 2 == 0)
print(t4[0:3,3:8])
print(t4[1:3,4:6])
print(t4[1:3,2:4])

[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]
[[ 4  5  6  7]
 [11 12 13 14]
 [18 19 20 21]]
[[12 13]
 [19 20]]
[[10 11]
 [17 18]]


In [104]:
# np 배열 연산
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print('덧셈 : ',np1+np2)
print('뺄셈 : ',np1-np2)
print('곱셈 : ',np1*np2)
print('나눗셈 : ',np1/np2)

덧셈 :  [ 7  9 11 13 15]
뺄셈 :  [5 5 5 5 5]
곱셈 :  [ 6 14 24 36 50]
나눗셈 :  [6.         3.5        2.66666667 2.25       2.        ]


In [106]:
# 브로드캐스팅
np3 = np1 + 10
print(np3)

[16 17 18 19 20]


In [114]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]).reshape(3,1)
print(br1)
print(br2)
# 스칼라와 연산
print(br1)
print(br1+3)
print(br1*2)
# 2D와 1D의 연산
print(br2)
print(br1+br2)
print(br1*br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11]
 [22]
 [33]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[11]
 [22]
 [33]]
[[12 13 14]
 [26 27 28]
 [40 41 42]]
[[ 11  22  33]
 [ 88 110 132]
 [231 264 297]]


In [116]:
br2.flatten()

array([11, 22, 33])

In [118]:
ff = np.arange(1,10).reshape(3,3)
print(ff.reshape(1,9))
print(ff.flatten())

[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]


## Random number 발생

 - np.random.randint(): 균일 분포의 정수 난수
 - np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
 - np.random.randn(): 표준 정규 분포 난수 생성
 - np.random.normal(): 정규 분포 난수 생성

In [2]:
# randomint
import numpy as np
x = np.random.randint(0,255,size=(3,3,3))
x

array([[[210, 161, 193],
        [236,   4,  44],
        [ 71, 120, 243]],

       [[178,  65, 209],
        [219, 108, 119],
        [ 82,  52, 217]],

       [[ 78,  98,  18],
        [ 90,  19, 161],
        [202,  68,  53]]], dtype=int32)

In [3]:
print('평균값 : ',np.mean(x),'표준편차 : ',np.std(x))

평균값 :  122.88888888888889 표준편차 :  73.07699305239815


In [4]:
print(len(x.flatten()))

27


In [11]:
y = np.array([0,1,2,3,4,5,6,7,12,15,25,64,23,0,0,1,2,3])
print(len(y))
print(np.count_nonzero(y))

18
15


In [9]:
x = np.random.rand(10,5)
x

array([[0.05424969, 0.26046615, 0.32989937, 0.41492161, 0.02697697],
       [0.89766519, 0.25862284, 0.95721348, 0.49274905, 0.67730388],
       [0.52079011, 0.32092194, 0.68184566, 0.01006611, 0.02795959],
       [0.79687778, 0.39583043, 0.90890458, 0.99306711, 0.42225015],
       [0.39489956, 0.23248511, 0.06092553, 0.9176478 , 0.65718571],
       [0.21866014, 0.65897912, 0.60100374, 0.26414702, 0.684813  ],
       [0.8915533 , 0.18263824, 0.8496779 , 0.25986865, 0.41533436],
       [0.14835227, 0.74817044, 0.699723  , 0.62125618, 0.38215105],
       [0.72031191, 0.12939354, 0.7817881 , 0.7091094 , 0.25141937],
       [0.84720149, 0.03946224, 0.04339986, 0.73890663, 0.57424799]])

In [14]:
x = np.random.normal(5,3,(10,5)) # 평균이, 표준편차 3
print(x)
print(np.mean(x),np.std(x),x.min(),x.max())

[[ 6.56801842  7.35130023 10.48160627  4.60407014  2.31718258]
 [ 2.21538106  3.4013381   6.51008003  4.30985155  6.15185537]
 [-2.03497025  8.80929888  4.61045128  4.04522405  2.10541303]
 [ 3.39766093 10.1940401   5.01308319  6.45348827  7.82485153]
 [ 6.56690066  4.95269032  2.86915337  9.45804504 10.97032116]
 [ 4.30584025  4.11421444  1.90357168  3.51307406  0.37804909]
 [ 3.44721653  8.773482    1.32561601  8.79308961  5.02165075]
 [ 7.13418334  5.9330808   6.09538515  9.51604023 10.59416444]
 [ 9.21379717  6.81626667  6.51790793  0.68253785  4.45317929]
 [ 4.65508695  4.77059951  5.02292926  0.91125681  3.88682033]]
5.3385075089867495 2.923563424914967 -2.0349702548527153 10.970321163650599


In [15]:
x = np.array([3,4,45,43,65,0,0,0,24362,6,45,432,562])
print('x의 개수',len(x))
print('x의 개수',np.count_nonzero(x))
print('x의 개수',len(x) - np.count_nonzero(x))


x의 개수 13
x의 개수 10
x의 개수 3


In [19]:
print(np.mean(x))
print(x.mean())
print(np.var(x))
print(x.var())
print(np.std(x))
print(x.std())
print(x.max())
print(x.min())
print(np.median(x))

1966.6923076923076
1966.6923076923076
41825944.21301774
41825944.21301774
6467.2980612476595
6467.2980612476595
24362
0
43.0


In [20]:
print(np.percentile(x,0))
print(np.percentile(x,25))
print(np.percentile(x,50))
print(np.percentile(x,75))
print(np.percentile(x,100))

0.0
3.0
43.0
65.0
24362.0


# 판다스

 - 시리즈(series)
 - 데이터프레임(dataframe)

In [1]:
import numpy as np
import pandas as pd

In [10]:
# 판다스 기초
data1 = np.arange(1,11)
print(data1)
data2 = pd.Series(data1)
print(data2, type(data2),data2.index, data2.values, data2.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64 <class 'pandas.core.series.Series'> RangeIndex(start=0, stop=10, step=1) [ 1  2  3  4  5  6  7  8  9 10] int64


In [8]:
data3 = pd.Series([1,2,3.14,4,5,6,7])
print(data3)

0    1.00
1    2.00
2    3.14
3    4.00
4    5.00
5    6.00
6    7.00
dtype: float64


In [9]:
data3 = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [16]:
# 판다스 시리즈 딕셔너리데이터
population_dict ={
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}
country = pd.Series(population_dict)
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)
print(country.loc['usa'])
print(country.iloc[3])

korea      5182
japan     12622
china    141178
usa       32976
dtype: int64 Index(['korea', 'japan', 'china', 'usa'], dtype='object') [  5182  12622 141178  32976]
1 (4,) 4
32976
32976


In [20]:
# 판다스 데이터 프레임
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['a','b','c'],columns=['A','B','C'])
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [109]:
#테스트
import numpy as np
import pandas as pd

# 두 개의 시리즈 데이터
print("인구수 시리즈 데이터 : ")
population_dict ={
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}
population = pd.Series(population_dict)
print(population)
print("GDP 시리즈 데이터 : ")
GDP_dict ={
    'korea':169320000,
    'japan':516700000,
    'china':140925000,
    'usa':2041280000
}
GDP = pd.Series(GDP_dict)
print(GDP)
print('='*25)
print("데이터 프레임 생성")
country = pd.DataFrame({'population':population,'gdp':GDP})
country
print(country.index, country.columns)
# print(country.values,country.shape,country.size,country.ndim)
# country.index.name = 'Country'
# country.columns.name = "Info"

인구수 시리즈 데이터 : 
korea      5182
japan     12622
china    141178
usa       32976
dtype: int64
GDP 시리즈 데이터 : 
korea     169320000
japan     516700000
china     140925000
usa      2041280000
dtype: int64
데이터 프레임 생성
Index(['korea', 'japan', 'china', 'usa'], dtype='object') Index(['population', 'gdp'], dtype='object')


In [35]:
# 데이터 프레임의 요소 접근 방법, loc, iloc
country.loc['korea'],country.loc['usa']
country.iloc[2],country.iloc[1]

(Info
 population       141178
 gdp           140925000
 Name: china, dtype: int64,
 Info
 population        12622
 gdp           516700000
 Name: japan, dtype: int64)

In [43]:
country.loc['korea':'japan',:'population'] # <= x <=

Info     population
Country            
korea          5182
japan         12622

In [44]:
country.iloc[0:2,:1] # <= x <

Info     population
Country            
korea          5182
japan         12622

In [57]:
country.iloc[1:4,1:2]

Info            gdp
Country            
japan     516700000
china     140925000
usa      2041280000

In [55]:
country.iloc[1:3,0:2]

Info     population        gdp
Country                       
japan         12622  516700000
china        141178  140925000

In [45]:
country

Info     population         gdp
Country                        
korea          5182   169320000
japan         12622   516700000
china        141178   140925000
usa           32976  2041280000

In [58]:
# 컬럼 추가
gdpper = country['gdp'] / country['population']
country['gdp_per'] = gdpper
country

Info     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326

In [63]:
# 행 추가
country.loc['india'] = [142261,150505000,12121212]
country.loc['india','gdp_per'] = country.loc['india','gdp']/country.loc['india','population']
country

Info     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326
india        142261   150505000   1057.949825

In [67]:
# 행 추가
country.loc['africa'] = [142261,150505000,12121212]
country.loc['africa','gdp_per'] = country.loc['africa','gdp']/country.loc['africa','population']
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142261.0  1.505050e+08   1057.949825
africa     142261.0  1.505050e+08   1057.949825

In [68]:
# 행추가 방법2
africa = pd.Series(data = [123456,7777777],index = ['population','gdp'])
country.loc['africa']=africa
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142261.0  1.505050e+08   1057.949825
africa     123456.0  7.777777e+06           NaN

In [69]:
country.isnull().sum()

Info
population    0
gdp           0
gdp_per       1
dtype: int64

In [ ]:
# 열 제거 drop('이름', axis=0)
country = country.drop('africa', axis=0)
country

In [83]:
# 테스트1
country[country['population'] > 140000]

Info     population          gdp      gdp_per
Country                                      
china      141178.0  140925000.0   998.207936
india      142261.0  150505000.0  1057.949825

In [85]:
# 테스트2 조건, 슬라이싱(loc, iloc 필수)
country[(country['population'] > 10000) & (country['population'] < 100000)].loc[:,:'population']

Info     population
Country            
japan       12622.0
usa         32976.0

In [169]:
#테스트
import numpy as np
import pandas as pd

# 두 개의 시리즈 데이터
print("이름 : ")
name_dict ={
    '0':"홍길동",
    '1':"박철수",
    '2':"김영희"
}
name = pd.Series(name_dict)
print(name)
print("국어 : ")
kor_dict ={
    '0':80,
    '1':60,
    '2':70
}
kor = pd.Series(kor_dict)
print(kor)

print("수학 : ")
math_dict ={
    '0':70,
    '1':70,
    '2':90
}
math = pd.Series(math_dict)
print(math)

print("영어 : ")
eng_dict ={
    '0':70,
    '1':70,
    '2':90
}
eng = pd.Series(eng_dict)
print(eng)


print('='*25)
print("데이터 프레임 생성")
result = pd.DataFrame({'이름':name,'국어':kor,'수학':math, '영어':eng})
result
# print(country.index, country.columns)
# print(country.values,country.shape,country.size,country.ndim)
# country.index.name = 'Country'
# country.columns.name = "Info"

이름 : 
0    홍길동
1    박철수
2    김영희
dtype: object
국어 : 
0    80
1    60
2    70
dtype: int64
수학 : 
0    70
1    70
2    90
dtype: int64
영어 : 
0    70
1    70
2    90
dtype: int64
데이터 프레임 생성


이름  국어  수학  영어
0  홍길동  80  70  70
1  박철수  60  70  70
2  김영희  70  90  90

In [170]:
result.iloc[1:2,0:3]

이름  국어  수학
1  박철수  60  70

In [175]:
result[result['국어'] >= 70]

이름  국어  수학  영어    평균
0  홍길동  80  70  70  73.0
2  김영희  70  90  90  83.0

In [174]:
# 컬럼 추가
avg = (result['국어']+result['수학']+result['영어']) / 3
result['평균'] = round(avg)
result

이름  국어  수학  영어    평균
0  홍길동  80  70  70  73.0
1  박철수  60  70  70  67.0
2  김영희  70  90  90  83.0
3  최자바  55  95  70  73.0

In [173]:
new = pd.Series(data = ["최자바",55,95,70,73],index = ['이름','국어','수학','영어','평균'])
result.loc['3']=new
result

이름  국어  수학  영어    평균
0  홍길동  80  70  70  73.0
1  박철수  60  70  70  67.0
2  김영희  70  90  90  83.0
3  최자바  55  95  70  73.0

In [ ]:
# 1

# 2
data = [
    {'이름':'홍길동', '국어' :80, '수학' :70, '영어' :80},
    {'이름':'박철수', '국어' :60,'수학' :70, '영어' :80},
    {'이름':'김영희', '국어':70,'수학':90, '영어' :80}]
df = pd.DataFrame(data)
df

#3
data = [
    ('홍길동',80,70,80),
    ('박철수',60,70,80),
    ('김영희',70,90,80)]
df = pd.DataFrame(data,columns=['이름','국어','수학','영어'])
df

# 4
import numpy as np
data0 = [
    ('홍길동',80,70,80),
    ('박철수',60,70,80),
    ('김영희',70,90,80)]
# data = np.array(data0)
data = np.array(['홍길동',80,70,80],['박철수',60,70,80],['김영희',70,90,80])
data

# 문제풀이

df.loc[1:1]
df.iloc[1:2]

df['평균'] = (df['국어'] + df['수학'] + df['영어'])/3
print('평균',df['평균'].dtype)
df.round()

# df.iloc[3] = ("최자바",55,95,70,77)
df.loc[3] = ("최자바",55,95,70,77)
df